echo "docker image name               : ${DOCKER_IMAGE_NAME}"
echo "os name                         : $(uname -o)"
echo "kernel version                  : $(uname -r)"
echo "target hardware platform        : $(uname -p)"
echo "user name                       : $(id -run)" 
echo "primary user group name         : $(id -rgn)"
echo "user id                         : $(id -ru)"
echo "primary user group id           : $(id -rg)"
echo "all groups user is member of    : $(groups)"
echo "user home directory             : $(echo ~)"
echo "properties of home directory    : $(ls -ld ~ | awk '{print $1, $3, $4, $9}')"
echo "initial working directory       : $(pwd)"
echo "properties of working directory : $(ls -ld $(pwd) | awk '{print $1, $3, $4, $9}')"
echo "user shell                      : $SHELL"
